version: "3"
services:
  redis:
    container_name: "meilisync_cache"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
