version: "3"
services:
  meilisync:
    restart: always
    container_name: "meilisync_db"
    image: "supabase/postgres:15.1.1.80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=MeiliSync
    ports:
      - "3000:5432"
    volumes:
      - ./dbData/meilisync:/var/lib/postgresql/data/
    networks:
      - my-network
networks:
  my-network:
    driver: bridge

